# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SIFIVE_CCACHE)	+= sifive_ccache.o
obj-$(CONFIG_SIFIVE_ECACHE_PMU)	+= sifive_ecache_pmu.o
obj-$(CONFIG_SIFIVE_PL2)	+= sifive_pl2_cache.o
obj-$(CONFIG_SIFIVE_WGCHECKER)	+= sifive_wg_checker.o
